default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/iplookup-development.sqlite3

test:
  <<: *default
  database: db/iplookup-test.sqlite3

production:
  <<: *default
  database: db/iplookup-production.sqlite3
