#!/bin/bash

echo "*******************************"
echo "* Download CSV files          *"
echo "*******************************"
cd /tmp
curl -LOk http://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.CSV.ZIP
curl -LOk http://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.IPV6.CSV.ZIP

echo "****************************"
echo "* Unzip CSV files          *"
echo "****************************"

# Ask user do you wanna install unzip tool
read -p " This project requires unzip. Do you want to install (y|n) " ans
if [[ ( "$ans" == "y" ) || ( "$ans" == "Y" ) ]]
then
  cd /tmp
  if [ "$(uname)" == "Darwin" ]; then
    brew install unzip
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sudo apt-get -y install unzip
  fi
fi

echo "****************************"
echo "* Unzip CSV files          *"
echo "****************************"
cd /tmp
unzip -o IP2LOCATION-LITE-DB1.CSV.ZIP
unzip -o IP2LOCATION-LITE-DB1.IPV6.CSV.ZIP
rm -rf IP2LOCATION-LITE-DB1.IPV6.CSV.ZIP IP2LOCATION-LITE-DB1.CSV.ZIP LICENSE-CC-BY-SA-4.0.TXT README_LITE.TXT

echo "*****************************************"
echo "* Import CSV files to database          *"
echo "*****************************************"
cd $PWD && FILE=/tmp/IP2LOCATION-LITE-DB1.csv rake import:ipaddrs
cd $PWD && FILE=/tmp/IP2LOCATION-LITE-DB1.IPV6.csv rake import:ipaddrs
rm -rf /tmp/IP2LOCATION-LITE-DB1.csv
rm -rf /tmp/IP2LOCATION-LITE-DB1.IPV6.csv
