#!/bin/bash

echo "*******************************"
echo "* Download CSV files          *"
echo "*******************************"
cd /tmp
sudo rm -rf /tmp/*
curl -LOk http://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.CSV.ZIP
curl -LOk http://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.IPV6.CSV.ZIP

echo "****************************"
echo "* Unzip CSV files          *"
echo "****************************"

# Ask user do you wanna install unzip tool
read -p " This project requires unzip. Do you want to install (y|n) " ans
if [[ ( "$ans" == "y" ) || ( "$ans" == "Y" ) ]]
then
  cd /tmp
  if [ "$(uname)" == "Darwin" ]; then
    brew install unzip
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sudo apt-get -y install unzip
  fi
fi

echo "****************************"
echo "* Unzip CSV files          *"
echo "****************************"
unzip -o IP2LOCATION-LITE-DB1.CSV.ZIP
unzip -o IP2LOCATION-LITE-DB1.IPV6.CSV.ZIP
rm -rf IP2LOCATION-LITE-DB1.IPV6.CSV.ZIP IP2LOCATION-LITE-DB1.CSV.ZIP LICENSE-CC-BY-SA-4.0.TXT README_LITE.TXT

echo "*****************************************"
echo "* Import CSV files to database          *"
echo "*****************************************"

# Need to replace the project path
rails_app_home () {
  cd /Users/vinhnguyen/Documents/projects/GitHub/roomorama/iplookup
}

rails_app_home && FILE=/tmp/IP2LOCATION-LITE-DB1.csv rake import:ipaddrs -s
rails_app_home && FILE=/tmp/IP2LOCATION-LITE-DB1.IPV6.csv rake import:ipaddrs -s

rm -rf /tmp/IP2LOCATION-LITE-DB1.csv
rm -rf /tmp/IP2LOCATION-LITE-DB1.IPV6.csv
